import type { RigDef } from "../core/rig-build";

/**
 * Built-in starter rigs.
 *
 * Conventions (kept deliberately simple so you can author your own):
 *  · space is y-down, angle 0 = facing right, +90 = down, -90 = up
 *  · every character faces right; a bone's `a` is its angle relative to its parent
 *  · the head bone points *forward* (toward the face) so face art can be authored along +x
 *  · part polygons are generated in bone space: x = along the bone, y = sideways
 */

const KID: RigDef = {
  id: "kid",
  label: "Walk Kid",
  hint: "Side view · IK hands & feet · walk-cycle demo",
  palette: "cartoon",
  root: { x: -6, y: 4 },
  ground: 72,
  frames: 24,
  fps: 24,
  demo: "walk",
  bg: ["#2b3060", "#171a30"],
  outline: "#221f2e",
  bones: [
    { id: "hips", d: "Hips", l: 0, a: 0, w: 5.5 },
    { id: "spine", d: "Spine", p: "hips", l: 32, a: -92, min: -22, max: 26 },
    { id: "chest", d: "Chest", p: "spine", l: 18, a: 6, min: -18, max: 20 },
    { id: "neck", d: "Neck", p: "chest", l: 9, a: -4, min: -26, max: 28 },
    { id: "head", d: "Head", p: "neck", l: 22, a: 84, min: -36, max: 36 },
    { id: "ear", d: "Ear", p: "head", l: 11, a: -120 },

    { id: "armUpF", d: "Upper arm", p: "chest", l: 26, a: 168, min: -26, max: 80 },
    { id: "armLoF", d: "Forearm", p: "armUpF", l: 24, a: 8, min: -124, max: 12 },
    { id: "handF", d: "Hand", p: "armLoF", l: 9, a: 0 },
    { id: "armUpB", d: "Upper arm · far", p: "chest", l: 25, a: 174, min: -26, max: 80 },
    { id: "armLoB", d: "Forearm · far", p: "armUpB", l: 23, a: 6, min: -124, max: 12 },
    { id: "handB", d: "Hand · far", p: "armLoB", l: 8, a: 0 },

    { id: "legUpF", d: "Thigh", p: "hips", l: 34, a: 88, min: -75, max: 70 },
    { id: "legLoF", d: "Shin", p: "legUpF", l: 32, a: -6, min: -6, max: 140 },
    { id: "footF", d: "Foot", p: "legLoF", l: 13, a: -80 },
    { id: "legUpB", d: "Thigh · far", p: "hips", l: 34, a: 94, min: -75, max: 70 },
    { id: "legLoB", d: "Shin · far", p: "legUpB", l: 32, a: -2, min: -6, max: 140 },
    { id: "footB", d: "Foot · far", p: "legLoB", l: 12, a: -82 },
  ],
  chains: [
    { id: "armF", d: "Arm IK · near", b: ["armUpF", "armLoF"], pole: true, color: "#7cf0c8" },
    { id: "armB", d: "Arm IK · far", b: ["armUpB", "armLoB"], pole: true, color: "#5ec8ff" },
    { id: "legF", d: "Leg IK · near", b: ["legUpF", "legLoF"], pole: true, color: "#ffb347" },
    { id: "legB", d: "Leg IK · far", b: ["legUpB", "legLoB"], pole: true, color: "#ff7a9c" },
  ],
  shapes: [
    { kind: "upperArm", bone: "armUpB", z: 0, fill: "#d99f76", name: "Far upper arm" },
    { kind: "foreArm", bone: "armLoB", z: 0, fill: "#d99f76", name: "Far forearm" },
    { kind: "hand", bone: "handB", z: 0, fill: "#d99f76", name: "Far hand" },
    { kind: "thigh", bone: "legUpB", z: 1, fill: "#2b408f", name: "Far thigh" },
    { kind: "shin", bone: "legLoB", z: 1, fill: "#2b408f", name: "Far shin" },
    { kind: "paw", bone: "footB", z: 1, scale: 1.15, fill: "#26263a", name: "Far shoe" },
    { kind: "ear", bone: "ear", z: 2, scale: 1.1, fill: "#eeb98f", name: "Ear" },
    { kind: "torso", bone: "spine", sx: 1.66, sy: 1.5, z: 3, role: "cloth", name: "Shirt" },
    { kind: "belly", bone: "spine", x: 12, y: 5, sx: 1.1, sy: 1.35, z: 4, role: "white", name: "Tummy" },
    { kind: "hipbox", bone: "spine", x: -6, sx: 0.62, sy: 1.85, z: 2, role: "cloth2", name: "Shorts" },
    { kind: "neck", bone: "neck", sx: 1.4, sy: 1.5, z: 5, role: "skin", name: "Neck" },
    { kind: "thigh", bone: "legUpF", z: 6, scale: 1.08, role: "cloth2", name: "Thigh" },
    { kind: "shin", bone: "legLoF", z: 6, role: "cloth2", name: "Shin" },
    { kind: "paw", bone: "footF", z: 7, scale: 1.3, role: "shoe", name: "Sneaker" },
    { kind: "sleeve", bone: "armUpF", z: 8, role: "cloth", name: "Sleeve" },
    { kind: "upperArm", bone: "armUpF", z: 8, scale: 1.05, role: "skin", name: "Upper arm" },
    { kind: "foreArm", bone: "armLoF", z: 8, scale: 1.05, role: "skin", name: "Forearm" },
    { kind: "hand", bone: "handF", z: 9, scale: 1.4, role: "skin", name: "Hand" },
    { kind: "head", bone: "head", scale: 1.18, x: -3, y: -1, z: 10, role: "skin", name: "Head" },
    { kind: "hairSpike", bone: "head", x: -6, y: -8, scale: 0.78, z: 11, role: "hair", name: "Hair" },
    { kind: "eye", bone: "head", x: 13, y: -4, scale: 0.95, z: 12, role: "white", name: "Eye" },
    { kind: "pupil", bone: "head", x: 17, y: -3, scale: 1.1, z: 13, role: "eye", name: "Pupil" },
    { kind: "mouth", bone: "head", x: 14, y: 6, scale: 1.1, rot: 6, z: 13, role: "dark", name: "Mouth" },
  ],
};

const ROBOT: RigDef = {
  id: "robot",
  label: "Bolt the Robot",
  hint: "3-bone arm IK (FABRIK) · mirrored limb pairs · wave demo",
  palette: "robot",
  root: { x: 0, y: 2 },
  ground: 70,
  frames: 32,
  fps: 24,
  demo: "wave",
  bg: ["#1c2438", "#0f1320"],
  outline: "#151a26",
  bones: [
    { id: "hips", d: "Hips", l: 0, a: -90, w: 5.5 },
    { id: "torso", d: "Torso", p: "hips", l: 46, a: 0, min: -18, max: 18 },
    { id: "head", d: "Head", p: "torso", l: 22, a: 90, min: -34, max: 34 },
    { id: "antenna", d: "Antenna", p: "head", l: 16, a: -108, min: -70, max: 70 },

    { id: "shL", d: "Shoulder", p: "torso", l: 12, a: 178, m: "shR", min: -90, max: 90 },
    { id: "armL", d: "Upper arm", p: "shL", l: 28, a: 6, m: "armR", min: -110, max: 110 },
    { id: "foreL", d: "Forearm", p: "armL", l: 26, a: -6, m: "foreR", min: -120, max: 14 },
    { id: "handL", d: "Hand", p: "foreL", l: 10, a: 0, m: "handR" },
    { id: "shR", d: "Shoulder · far", p: "torso", l: 12, a: 172, m: "shL", min: -90, max: 90 },
    { id: "armR", d: "Upper arm · far", p: "shR", l: 27, a: 4, m: "armL", min: -110, max: 110 },
    { id: "foreR", d: "Forearm · far", p: "armR", l: 25, a: -4, m: "foreL", min: -120, max: 14 },
    { id: "handR", d: "Hand · far", p: "foreR", l: 9, a: 0, m: "handL" },

    { id: "thL", d: "Thigh", p: "hips", l: 32, a: 178, m: "thR", min: -50, max: 50 },
    { id: "shinL", d: "Shin", p: "thL", l: 30, a: -4, m: "shinR", min: -130, max: 6 },
    { id: "ftL", d: "Foot", p: "shinL", l: 14, a: -84, m: "ftR" },
    { id: "thR", d: "Thigh · far", p: "hips", l: 32, a: 174, m: "thL", min: -50, max: 50 },
    { id: "shinR", d: "Shin · far", p: "thR", l: 30, a: 2, m: "shinL", min: -130, max: 6 },
    { id: "ftR", d: "Foot · far", p: "shinR", l: 13, a: -82, m: "ftL" },
  ],
  chains: [
    { id: "armChainL", d: "Arm IK (3 bones)", b: ["shL", "armL", "foreL"], pole: false, color: "#7cf0c8", m: "armChainR" },
    { id: "armChainR", d: "Arm IK · far", b: ["shR", "armR", "foreR"], pole: false, color: "#5ec8ff", m: "armChainL" },
    { id: "legL", d: "Leg IK", b: ["thL", "shinL"], pole: true, color: "#ffb347", m: "legR" },
    { id: "legR", d: "Leg IK · far", b: ["thR", "shinR"], pole: true, color: "#ff7a9c", m: "legL" },
  ],
  shapes: [
    { kind: "upperArm", bone: "armR", z: 0, scale: 1.05, fill: "#8b9bb5", name: "Far upper arm" },
    { kind: "foreArm", bone: "foreR", z: 0, fill: "#b6c4d8", name: "Far forearm" },
    { kind: "ball", bone: "handR", z: 0, scale: 1.5, fill: "#b6c4d8", name: "Far hand" },
    { kind: "ball", bone: "shR", z: 0, scale: 1.6, fill: "#6f7f99", name: "Far shoulder" },
    { kind: "thigh", bone: "thR", z: 1, scale: 1.1, fill: "#6b7a94", name: "Far thigh" },
    { kind: "shin", bone: "shinR", z: 1, scale: 1.05, fill: "#8b9bb5", name: "Far shin" },
    { kind: "hoof", bone: "ftR", z: 1, scale: 1.5, fill: "#2c3444", name: "Far foot" },
    { kind: "hipbox", bone: "hips", z: 3, role: "cloth2", name: "Pelvis", sx: 1.1, sy: 2.6 },
    { kind: "rectPanel", bone: "torso", z: 4, role: "skin", name: "Body", pts: [{ x: -2, y: -23 }, { x: 44, y: -26 }, { x: 48, y: 26 }, { x: -6, y: 23 }] },
    { kind: "pupil", bone: "torso", z: 5, scale: 2.6, x: 24, role: "accent", name: "Chest light" },
    { kind: "thigh", bone: "thL", z: 6, role: "cloth", name: "Thigh", scale: 1.2 },
    { kind: "shin", bone: "shinL", z: 6, role: "cloth2", name: "Shin", scale: 1.15 },
    { kind: "hoof", bone: "ftL", z: 7, role: "dark", name: "Foot", scale: 1.7 },
    { kind: "ball", bone: "shL", z: 8, scale: 1.7, role: "cloth", name: "Shoulder pad" },
    { kind: "upperArm", bone: "armL", z: 8, role: "cloth2", name: "Upper arm", scale: 1.2 },
    { kind: "foreArm", bone: "foreL", z: 8, role: "skin", name: "Forearm", scale: 1.15 },
    { kind: "ball", bone: "handL", z: 9, scale: 1.7, role: "white", name: "Hand" },
    { kind: "rectPanel", bone: "head", z: 10, role: "skin", name: "Head box", pts: [{ x: -6, y: -15 }, { x: 22, y: -16 }, { x: 24, y: 15 }, { x: -8, y: 14 }] },
    { kind: "rectPanel", bone: "head", z: 11, role: "dark", name: "Visor", pts: [{ x: 6, y: -11 }, { x: 19, y: -10 }, { x: 19, y: 10 }, { x: 6, y: 11 }] },
    { kind: "pupil", bone: "head", z: 12, scale: 2.6, x: 13, y: -5, role: "eye", name: "Eye" },
    { kind: "pupil", bone: "head", z: 12, scale: 1.9, x: 13, y: 4, role: "eye", name: "Eye 2" },
    { kind: "tail", bone: "antenna", z: 9, role: "cloth2", name: "Antenna", sx: 1.2, sy: 0.4 },
    { kind: "spark", bone: "antenna", z: 10, scale: 1.2, x: 15, role: "accent", name: "Antenna bulb" },
  ],
};

const DRAGON: RigDef = {
  id: "dragon",
  label: "Ember the Dragon",
  hint: "4-bone tail IK with follow-through · wings · flight demo",
  palette: "dragon",
  root: { x: 6, y: 0 },
  ground: null,
  frames: 28,
  fps: 24,
  demo: "flight",
  bg: ["#3a2a55", "#1a1430"],
  outline: "#1a2418",
  bones: [
    { id: "hips", d: "Hips", l: 0, a: 0, w: 5.5 },
    { id: "body", d: "Body", p: "hips", l: 46, a: -4, min: -16, max: 16 },
    { id: "neck", d: "Neck", p: "body", l: 20, a: -30, min: -34, max: 34 },
    { id: "head", d: "Head", p: "neck", l: 24, a: 22, min: -34, max: 34 },
    { id: "jaw", d: "Jaw", p: "head", l: 14, a: 18, min: -4, max: 34 },
    { id: "horn", d: "Horn", p: "head", l: 14, a: -78 },
    { id: "wingUp", d: "Wing arm", p: "body", l: 26, a: -108, min: -85, max: 60 },
    { id: "wingLo", d: "Wing fore", p: "wingUp", l: 32, a: 22, min: -75, max: 75 },
    { id: "legUpF", d: "Leg", p: "hips", l: 24, a: 74, min: -50, max: 40 },
    { id: "legLoF", d: "Shin", p: "legUpF", l: 22, a: 26, min: -10, max: 110 },
    { id: "clawF", d: "Claw", p: "legLoF", l: 10, a: -50 },
    { id: "legUpB", d: "Leg · far", p: "body", l: 24, a: 78, min: -50, max: 40 },
    { id: "legLoB", d: "Shin · far", p: "legUpB", l: 22, a: 22, min: -10, max: 110 },
    { id: "clawB", d: "Claw · far", p: "legLoB", l: 9, a: -50 },
    { id: "tail1", d: "Tail 1", p: "hips", l: 24, a: 176, min: -50, max: 50 },
    { id: "tail2", d: "Tail 2", p: "tail1", l: 22, a: 8, min: -44, max: 44 },
    { id: "tail3", d: "Tail 3", p: "tail2", l: 20, a: 8, min: -42, max: 42 },
    { id: "tail4", d: "Tail tip", p: "tail3", l: 18, a: 8, min: -42, max: 42 },
  ],
  chains: [
    { id: "tail", d: "Tail IK (4 bones)", b: ["tail1", "tail2", "tail3", "tail4"], pole: false, color: "#ffd166" },
    { id: "legF", d: "Leg IK", b: ["legUpF", "legLoF"], pole: true, color: "#7cf0c8" },
    { id: "legB", d: "Leg IK · far", b: ["legUpB", "legLoB"], pole: true, color: "#5ec8ff" },
  ],
  shapes: [
    { kind: "tail", bone: "tail1", z: 0, role: "cloth", name: "Tail 1", sy: 1.3 },
    { kind: "tail", bone: "tail2", z: 0, role: "cloth", name: "Tail 2", scale: 0.95 },
    { kind: "tail", bone: "tail3", z: 0, role: "cloth", name: "Tail 3", scale: 0.85 },
    { kind: "tailTuft", bone: "tail4", z: 0, role: "accent", name: "Tail flame", scale: 1.1 },
    { kind: "wing", bone: "wingUp", z: 1, fill: "#2f7f55", name: "Far wing", sx: 1.9, sy: 1.7 },
    { kind: "thigh", bone: "legUpB", z: 1, fill: "#3d8a5e", name: "Far thigh" },
    { kind: "shin", bone: "legLoB", z: 1, fill: "#3d8a5e", name: "Far shin" },
    { kind: "paw", bone: "clawB", z: 1, fill: "#2f6b49", name: "Far claw" },
    { kind: "shell", bone: "body", z: 4, role: "skin", name: "Body", sx: 1.5, sy: 1.25, x: 4 },
    { kind: "belly", bone: "body", z: 5, role: "accent", name: "Belly", sx: 1.35, sy: 1.0, x: 8, y: 10 },
    { kind: "thigh", bone: "legUpF", z: 6, role: "cloth", name: "Thigh", scale: 1.1 },
    { kind: "shin", bone: "legLoF", z: 6, role: "cloth", name: "Shin", scale: 1.05 },
    { kind: "paw", bone: "clawF", z: 6, role: "dark", name: "Claw" },
    { kind: "neck", bone: "neck", z: 7, role: "skin", name: "Neck", sx: 1.2, sy: 1.6 },
    { kind: "wing", bone: "wingUp", z: 8, role: "cloth2", name: "Wing", sx: 1.85, sy: 1.6, x: 1 },
    { kind: "wing", bone: "wingLo", z: 8, role: "cloth2", name: "Wing tip", sx: 1.5, sy: 1.3, x: -6 },
    { kind: "head", bone: "head", z: 9, role: "skin", name: "Skull", sx: 1.5, sy: 1.15, x: -2, y: -2 },
    { kind: "snout", bone: "head", z: 10, role: "skin", name: "Snout", scale: 0.85, x: 18, y: 3 },
    { kind: "jaw", bone: "jaw", z: 10, role: "cloth2", name: "Jaw", scale: 1.05 },
    { kind: "horn", bone: "horn", z: 9, role: "accent", name: "Horn", scale: 1.0 },
    { kind: "eye", bone: "head", z: 11, role: "white", name: "Eye", scale: 1.1, x: 10, y: -8 },
    { kind: "pupil", bone: "head", z: 12, role: "eye", name: "Pupil", scale: 1.1, x: 13, y: -7 },
  ],
};

const BLOB: RigDef = {
  id: "blob",
  label: "Gloop the Blob",
  hint: "Squash & stretch body IK · wobbly antenna IK · bounce demo",
  palette: "blob",
  root: { x: 0, y: 30 },
  ground: 78,
  frames: 24,
  fps: 24,
  demo: "bounce",
  bg: ["#1f4038", "#10231f"],
  outline: "#12312a",
  bones: [
    { id: "hips", d: "Base", l: 0, a: -90, w: 5.5 },
    { id: "body1", d: "Body lower", p: "hips", l: 30, a: 0, min: -44, max: 44 },
    { id: "body2", d: "Body upper", p: "body1", l: 26, a: 0, min: -50, max: 50 },
    { id: "head", d: "Head", p: "body2", l: 22, a: 92, min: -44, max: 44 },
    { id: "ant1", d: "Antenna 1", p: "head", l: 14, a: -110, min: -80, max: 80 },
    { id: "ant2", d: "Antenna 2", p: "ant1", l: 12, a: 0, min: -80, max: 80 },
    { id: "ant3", d: "Antenna tip", p: "ant2", l: 11, a: 0, min: -80, max: 80 },
    { id: "armUpL", d: "Arm", p: "body2", l: 20, a: 150, min: -130, max: 130 },
    { id: "armLoL", d: "Hand", p: "armUpL", l: 14, a: 10, min: -130, max: 130 },
    { id: "armUpR", d: "Arm · far", p: "body2", l: 20, a: 162, min: -130, max: 130 },
    { id: "armLoR", d: "Hand · far", p: "armUpR", l: 13, a: 8, min: -130, max: 130 },
  ],
  chains: [
    { id: "body", d: "Body IK (drag = squish!)", b: ["body1", "body2"], pole: false, color: "#7cf0c8" },
    { id: "antenna", d: "Antenna IK", b: ["ant1", "ant2", "ant3"], pole: false, color: "#ffd166" },
    { id: "armL", d: "Arm IK", b: ["armUpL", "armLoL"], pole: false, color: "#5ec8ff" },
    { id: "armR", d: "Arm IK · far", b: ["armUpR", "armLoR"], pole: false, color: "#ff7a9c" },
  ],
  shapes: [
    { kind: "upperArm", bone: "armUpR", z: 0, fill: "#57b899", name: "Far arm" },
    { kind: "hand", bone: "armLoR", z: 0, scale: 1.2, fill: "#57b899", name: "Far hand" },
    { kind: "shell", bone: "body1", z: 2, role: "skin", name: "Lower blob", sx: 2.3, sy: 1.9, x: 0 },
    { kind: "shell", bone: "body2", z: 3, role: "skin", name: "Upper blob", sx: 2.0, sy: 1.7, x: 0 },
    { kind: "belly", bone: "body1", z: 4, role: "white", name: "Tummy", sx: 1.7, sy: 1.3, x: 6, y: 6 },
    { kind: "tail", bone: "ant1", z: 5, role: "cloth2", name: "Antenna", sx: 1.6, sy: 0.5 },
    { kind: "upperArm", bone: "armUpL", z: 6, role: "cloth", name: "Arm", scale: 1.1 },
    { kind: "hand", bone: "armLoL", z: 6, scale: 1.35, role: "cloth", name: "Hand" },
    { kind: "spark", bone: "ant3", z: 7, scale: 1.3, x: 6, role: "accent", name: "Antenna spark" },
    { kind: "head", bone: "head", z: 8, role: "skin", name: "Head", sx: 1.9, sy: 1.7, x: -4 },
    { kind: "eye", bone: "head", z: 9, role: "white", name: "Eye", scale: 1.7, x: 12, y: -5 },
    { kind: "pupil", bone: "head", z: 10, role: "eye", name: "Pupil", scale: 1.7, x: 15, y: -4 },
    { kind: "mouth", bone: "head", z: 10, role: "dark", name: "Mouth", scale: 1.5, x: 12, y: 7 },
  ],
};

const BLANK: RigDef = {
  id: "blank",
  label: "Empty stage",
  hint: "Start from nothing: add bones, drop parts on them",
  palette: "cartoon",
  root: { x: 0, y: 40 },
  ground: 100,
  frames: 48,
  fps: 24,
  demo: null,
  bg: ["#262a4a", "#14162a"],
  bones: [{ id: "hips", d: "Hips", l: 0, a: 0, w: 5.5 }],
  shapes: [{ kind: "hipbox", bone: "hips", z: 0, role: "cloth2", name: "Base", sx: 1.8, sy: 1.4 }],
};

export const RIGS: RigDef[] = [KID, ROBOT, DRAGON, BLOB, BLANK];
export const RIG_MAP = new Map(RIGS.map((r) => [r.id, r]));
