import type { RigDef } from "../core/rig-build";

/**
 * Built-in starter rigs.
 *
 * Conventions (kept deliberately simple so you can author your own):
 *  · space is y-down, angle 0 = facing right, +90 = down, -90 = up
 *  · every character faces right; a bone's `a` is its angle relative to its parent
 *  · the head bone points *forward* (toward the face) so face art can be authored along +x
 *  · part polygons are generated in bone space: x = along the bone, y = sideways
 */

const KID: RigDef = {
  id: "kid",
  label: "Walk Kid",
  hint: "Side view · IK hands & feet · walk-cycle demo",
  palette: "cartoon",
  root: { x: -6, y: 4 },
  ground: 72,
  frames: 24,
  fps: 24,
  demo: "walk",
  bg: ["#2b3060", "#171a30"],
  outline: "#221f2e",
  bones: [
    { id: "hips", d: "Hips", l: 0, a: 0, w: 5.5 },
    { id: "spine", d: "Spine", p: "hips", l: 32, a: -92, min: -22, max: 26 },
    { id: "chest", d: "Chest", p: "spine", l: 18, a: 6, min: -18, max: 20 },
    { id: "neck", d: "Neck", p: "chest", l: 9, a: -4, min: -26, max: 28 },
    { id: "head", d: "Head", p: "neck", l: 22, a: 84, min: -36, max: 36 },
    { id: "ear", d: "Ear", p: "head", l: 11, a: -120 },

    { id: "armUpF", d: "Upper arm", p: "chest", l: 26, a: 168, min: -26, max: 80 },
    { id: "armLoF", d: "Forearm", p: "armUpF", l: 24, a: 8, min: -124, max: 12 },
    { id: "handF", d: "Hand", p: "armLoF", l: 9, a: 0 },
    { id: "armUpB", d: "Upper arm · far", p: "chest", l: 25, a: 174, min: -26, max: 80 },
    { id: "armLoB", d: "Forearm · far", p: "armUpB", l: 23, a: 6, min: -124, max: 12 },
    { id: "handB", d: "Hand · far", p: "armLoB", l: 8, a: 0 },

    { id: "legUpF", d: "Thigh", p: "hips", l: 34, a: 88, min: -75, max: 70 },
    { id: "legLoF", d: "Shin", p: "legUpF", l: 32, a: -6, min: -6, max: 140 },
    { id: "footF", d: "Foot", p: "legLoF", l: 13, a: -80 },
    { id: "legUpB", d: "Thigh · far", p: "hips", l: 34, a: 94, min: -75, max: 70 },
    { id: "legLoB", d: "Shin · far", p: "legUpB", l: 32, a: -2, min: -6, max: 140 },
    { id: "footB", d: "Foot · far", p: "legLoB", l: 12, a: -82 },
  ],
  chains: [
    { id: "armF", d: "Arm IK · near", b: ["armUpF", "armLoF"], pole: true, color: "#7cf0c8" },
    { id: "armB", d: "Arm IK · far", b: ["armUpB", "armLoB"], pole: true, color: "#5ec8ff" },
    { id: "legF", d: "Leg IK · near", b: ["legUpF", "legLoF"], pole: true, color: "#ffb347" },
    { id: "legB", d: "Leg IK · far", b: ["legUpB", "legLoB"], pole: true, color: "#ff7a9c" },
  ],
  shapes: [
    { kind: "upperArm", bone: "armUpB", z: 0, fill: "#d99f76", name: "Far upper arm" },
    { kind: "foreArm", bone: "armLoB", z: 0, fill: "#d99f76", name: "Far forearm" },
    { kind: "hand", bone: "handB", z: 0, fill: "#d99f76", name: "Far hand" },
    { kind: "thigh", bone: "legUpB", z: 1, fill: "#2b408f", name: "Far thigh" },
    { kind: "shin", bone: "legLoB", z: 1, fill: "#2b408f", name: "Far shin" },
    { kind: "paw", bone: "footB", z: 1, scale: 1.15, fill: "#26263a", name: "Far shoe" },
    { kind: "ear", bone: "ear", z: 2, scale: 1.1, fill: "#eeb98f", name: "Ear" },
    { kind: "torso", bone: "spine", sx: 1.66, sy: 1.5, z: 3, role: "cloth", name: "Shirt" },
    { kind: "belly", bone: "spine", x: 12, y: 5, sx: 1.1, sy: 1.35, z: 4, role: "white", name: "Tummy" },
    { kind: "hipbox", bone: "spine", x: -6, sx: 0.62, sy: 1.85, z: 2, role: "cloth2", name: "Shorts" },
    { kind: "neck", bone: "neck", sx: 1.4, sy: 1.5, z: 5, role: "skin", name: "Neck" },
    { kind: "thigh", bone: "legUpF", z: 6, scale: 1.08, role: "cloth2", name: "Thigh" },
    { kind: "shin", bone: "legLoF", z: 6, role: "cloth2", name: "Shin" },
    { kind: "paw", bone: "footF", z: 7, scale: 1.3, role: "shoe", name: "Sneaker" },
    { kind: "sleeve", bone: "armUpF", z: 8, role: "cloth", name: "Sleeve" },
    { kind: "upperArm", bone: "armUpF", z: 8, scale: 1.05, role: "skin", name: "Upper arm" },
    { kind: "foreArm", bone: "armLoF", z: 8, scale: 1.05, role: "skin", name: "Forearm" },
    { kind: "hand", bone: "handF", z: 9, scale: 1.4, role: "skin", name: "Hand" },
    { kind: "head", bone: "head", scale: 1.18, x: -3, y: -1, z: 10, role: "skin", name: "Head" },
    { kind: "hairSpike", bone: "head", x: -6, y: -8, scale: 0.78, z: 11, role: "hair", name: "Hair" },
    { kind: "eye", bone: "head", x: 13, y: -4, scale: 0.95, z: 12, role: "white", name: "Eye" },
    { kind: "pupil", bone: "head", x: 17, y: -3, scale: 1.1, z: 13, role: "eye", name: "Pupil" },
    { kind: "mouth", bone: "head", x: 14, y: 6, scale: 1.1, rot: 6, z: 13, role: "dark", name: "Mouth" },
  ],
};

const ROBOT: RigDef = {
  id: "robot",
  label: "Bolt the Robot",
  hint: "3-bone arm IK (FABRIK) · mirrored limb pairs · wave demo",
  palette: "robot",
  root: { x: 0, y: 2 },
  ground: 70,
  frames: 32,
  fps: 24,
  demo: "wave",
  bg: ["#1c2438", "#0f1320"],
  outline: "#151a26",
  bones: [
    { id: "hips", d: "Hips", l: 0, a: -90, w: 5.5 },
    { id: "torso", d: "Torso", p: "hips", l: 46, a: 0, min: -18, max: 18 },
    { id: "head", d: "Head", p: "torso", l: 22, a: 90, min: -34, max: 34 },
    { id: "antenna", d: "Antenna", p: "head", l: 16, a: -108, min: -70, max: 70 },

    { id: "shL", d: "Shoulder", p: "torso", l: 12, a: 178, m: "shR", min: -90, max: 90 },
    { id: "armL", d: "Upper arm", p: "shL", l: 28, a: 6, m: "armR", min: -110, max: 110 },
    { id: "foreL", d: "Forearm", p: "armL", l: 26, a: -6, m: "foreR", min: -120, max: 14 },
    { id: "handL", d: "Hand", p: "foreL", l: 10, a: 0, m: "handR" },
    { id: "shR", d: "Shoulder · far", p: "torso", l: 12, a: 172, m: "shL", min: -90, max: 90 },
    { id: "armR", d: "Upper arm · far", p: "shR", l: 27, a: 4, m: "armL", min: -110, max: 110 },
    { id: "foreR", d: "Forearm · far", p: "armR", l: 25, a: -4, m: "foreL", min: -120, max: 14 },
    { id: "handR", d: "Hand · far", p: "foreR", l: 9, a: 0, m: "handL" },

    { id: "thL", d: "Thigh", p: "hips", l: 32, a: 178, m: "thR", min: -50, max: 50 },
    { id: "shinL", d: "Shin", p: "thL", l: 30, a: -4, m: "shinR", min: -130, max: 6 },
    { id: "ftL", d: "Foot", p: "shinL", l: 14, a: -84, m: "ftR" },
    { id: "thR", d: "Thigh · far", p: "hips", l: 32, a: 174, m: "thL", min: -50, max: 50 },
    { id: "shinR", d: "Shin · far", p: "thR", l: 30, a: 2, m: "shinL", min: -130, max: 6 },
    { id: "ftR", d: "Foot · far", p: "shinR", l: 13, a: -82, m: "ftL" },
  ],
  chains: [
    { id: "armChainL", d: "Arm IK (3 bones)", b: ["shL", "armL", "foreL"], pole: false, color: "#7cf0c8", m: "armChainR" },
    { id: "armChainR", d: "Arm IK · far", b: ["shR", "armR", "foreR"], pole: false, color: "#5ec8ff", m: "armChainL" },
    { id: "legL", d: "Leg IK", b: ["thL", "shinL"], pole: true, color: "#ffb347", m: "legR" },
    { id: "legR", d: "Leg IK · far", b: ["thR", "shinR"], pole: true, color: "#ff7a9c", m: "legL" },
  ],
  shapes: [
    { kind: "upperArm", bone: "armR", z: 0, scale: 1.05, fill: "#8b9bb5", name: "Far upper arm" },
    { kind: "foreArm", bone: "foreR", z: 0, fill: "#b6c4d8", name: "Far forearm" },
    { kind: "ball", bone: "handR", z: 0, scale: 1.5, fill: "#b6c4d8", name: "Far hand" },
    { kind: "ball", bone: "shR", z: 0, scale: 1.6, fill: "#6f7f99", name: "Far shoulder" },
    { kind: "thigh", bone: "thR", z: 1, scale: 1.1, fill: "#6b7a94", name: "Far thigh" },
    { kind: "shin", bone: "shinR", z: 1, scale: 1.05, fill: "#8b9bb5", name: "Far shin" },
    { kind: "hoof", bone: "ftR", z: 1, scale: 1.5, fill: "#2c3444", name: "Far foot" },
    { kind: "hipbox", bone: "hips", z: 3, role: "cloth2", name: "Pelvis", sx: 1.1, sy: 2.6 },
    { kind: "rectPanel", bone: "torso", z: 4, role: "skin", name: "Body", pts: [{ x: -2, y: -23 }, { x: 44, y: -26 }, { x: 48, y: 26 }, { x: -6, y: 23 }] },
    { kind: "pupil", bone: "torso", z: 5, scale: 2.6, x: 24, role: "accent", name: "Chest light" },
    { kind: "thigh", bone: "thL", z: 6, role: "cloth", name: "Thigh", scale: 1.2 },
    { kind: "shin", bone: "shinL", z: 6, role: "cloth2", name: "Shin", scale: 1.15 },
    { kind: "hoof", bone: "ftL", z: 7, role: "dark", name: "Foot", scale: 1.7 },
    { kind: "ball", bone: "shL", z: 8, scale: 1.7, role: "cloth", name: "Shoulder pad" },
    { kind: "upperArm", bone: "armL", z: 8, role: "cloth2", name: "Upper arm", scale: 1.2 },
    { kind: "foreArm", bone: "foreL", z: 8, role: "skin", name: "Forearm", scale: 1.15 },
    { kind: "ball", bone: "handL", z: 9, scale: 1.7, role: "white", name: "Hand" },
    { kind: "rectPanel", bone: "head", z: 10, role: "skin", name: "Head box", pts: [{ x: -6, y: -15 }, { x: 22, y: -16 }, { x: 24, y: 15 }, { x: -8, y: 14 }] },
    { kind: "rectPanel", bone: "head", z: 11, role: "dark", name: "Visor", pts: [{ x: 6, y: -11 }, { x: 19, y: -10 }, { x: 19, y: 10 }, { x: 6, y: 11 }] },
    { kind: "pupil", bone: "head", z: 12, scale: 2.6, x: 13, y: -5, role: "eye", name: "Eye" },
    { kind: "pupil", bone: "head", z: 12, scale: 1.9, x: 13, y: 4, role: "eye", name: "Eye 2" },
    { kind: "tail", bone: "antenna", z: 9, role: "cloth2", name: "Antenna", sx: 1.2, sy: 0.4 },
    { kind: "spark", bone: "antenna", z: 10, scale: 1.2, x: 15, role: "accent", name: "Antenna bulb" },
  ],
};

const DRAGON: RigDef = {
  id: "dragon",
  label: "Ember the Dragon",
  hint: "4-bone tail IK with follow-through · wings · flight demo",
  palette: "dragon",
  root: { x: 6, y: 0 },
  ground: null,
  frames: 28,
  fps: 24,
  demo: "flight",
  bg: ["#3a2a55", "#1a1430"],
  outline: "#1a2418",
  bones: [
    { id: "hips", d: "Hips", l: 0, a: 0, w: 5.5 },
    { id: "body", d: "Body", p: "hips", l: 46, a: -4, min: -16, max: 16 },
    { id: "neck", d: "Neck", p: "body", l: 20, a: -30, min: -34, max: 34 },
    { id: "head", d: "Head", p: "neck", l: 24, a: 22, min: -34, max: 34 },
    { id: "jaw", d: "Jaw", p: "head", l: 14, a: 18, min: -4, max: 34 },
    { id: "horn", d: "Horn", p: "head", l: 14, a: -78 },
    { id: "wingUp", d: "Wing arm", p: "body", l: 26, a: -108, min: -85, max: 60 },
    { id: "wingLo", d: "Wing fore", p: "wingUp", l: 32, a: 22, min: -75, max: 75 },
    { id: "legUpF", d: "Leg", p: "hips", l: 24, a: 74, min: -50, max: 40 },
    { id: "legLoF", d: "Shin", p: "legUpF", l: 22, a: 26, min: -10, max: 110 },
    { id: "clawF", d: "Claw", p: "legLoF", l: 10, a: -50 },
    { id: "legUpB", d: "Leg · far", p: "body", l: 24, a: 78, min: -50, max: 40 },
    { id: "legLoB", d: "Shin · far", p: "legUpB", l: 22, a: 22, min: -10, max: 110 },
    { id: "clawB", d: "Claw · far", p: "legLoB", l: 9, a: -50 },
    { id: "tail1", d: "Tail 1", p: "hips", l: 24, a: 176, min: -50, max: 50 },
    { id: "tail2", d: "Tail 2", p: "tail1", l: 22, a: 8, min: -44, max: 44 },
    { id: "tail3", d: "Tail 3", p: "tail2", l: 20, a: 8, min: -42, max: 42 },
    { id: "tail4", d: "Tail tip", p: "tail3", l: 18, a: 8, min: -42, max: 42 },
  ],
  chains: [
    { id: "tail", d: "Tail IK (4 bones)", b: ["tail1", "tail2", "tail3", "tail4"], pole: false, color: "#ffd166" },
    { id: "legF", d: "Leg IK", b: ["legUpF", "legLoF"], pole: true, color: "#7cf0c8" },
    { id: "legB", d: "Leg IK · far", b: ["legUpB", "legLoB"], pole: true, color: "#5ec8ff" },
  ],
  shapes: [
    { kind: "tail", bone: "tail1", z: 0, role: "cloth", name: "Tail 1", sy: 1.3 },
    { kind: "tail", bone: "tail2", z: 0, role: "cloth", name: "Tail 2", scale: 0.95 },
    { kind: "tail", bone: "tail3", z: 0, role: "cloth", name: "Tail 3", scale: 0.85 },
    { kind: "tailTuft", bone: "tail4", z: 0, role: "accent", name: "Tail flame", scale: 1.1 },
    { kind: "wing", bone: "wingUp", z: 1, fill: "#2f7f55", name: "Far wing", sx: 1.9, sy: 1.7 },
    { kind: "thigh", bone: "legUpB", z: 1, fill: "#3d8a5e", name: "Far thigh" },
    { kind: "shin", bone: "legLoB", z: 1, fill: "#3d8a5e", name: "Far shin" },
    { kind: "paw", bone: "clawB", z: 1, fill: "#2f6b49", name: "Far claw" },
    { kind: "shell", bone: "body", z: 4, role: "skin", name: "Body", sx: 1.5, sy: 1.25, x: 4 },
    { kind: "belly", bone: "body", z: 5, role: "accent", name: "Belly", sx: 1.35, sy: 1.0, x: 8, y: 10 },
    { kind: "thigh", bone: "legUpF", z: 6, role: "cloth", name: "Thigh", scale: 1.1 },
    { kind: "shin", bone: "legLoF", z: 6, role: "cloth", name: "Shin", scale: 1.05 },
    { kind: "paw", bone: "clawF", z: 6, role: "dark", name: "Claw" },
    { kind: "neck", bone: "neck", z: 7, role: "skin", name: "Neck", sx: 1.2, sy: 1.6 },
    { kind: "wing", bone: "wingUp", z: 8, role: "cloth2", name: "Wing", sx: 1.85, sy: 1.6, x: 1 },
    { kind: "wing", bone: "wingLo", z: 8, role: "cloth2", name: "Wing tip", sx: 1.5, sy: 1.3, x: -6 },
    { kind: "head", bone: "head", z: 9, role: "skin", name: "Skull", sx: 1.5, sy: 1.15, x: -2, y: -2 },
    { kind: "snout", bone: "head", z: 10, role: "skin", name: "Snout", scale: 0.85, x: 18, y: 3 },
    { kind: "jaw", bone: "jaw", z: 10, role: "cloth2", name: "Jaw", scale: 1.05 },
    { kind: "horn", bone: "horn", z: 9, role: "accent", name: "Horn", scale: 1.0 },
    { kind: "eye", bone: "head", z: 11, role: "white", name: "Eye", scale: 1.1, x: 10, y: -8 },
    { kind: "pupil", bone: "head", z: 12, role: "eye", name: "Pupil", scale: 1.1, x: 13, y: -7 },
  ],
};

const BLOB: RigDef = {
  id: "blob",
  label: "Gloop the Blob",
  hint: "Squash & stretch body IK · wobbly antenna IK · bounce demo",
  palette: "blob",
  root: { x: 0, y: 30 },
  ground: 78,
  frames: 24,
  fps: 24,
  demo: "bounce",
  bg: ["#1f4038", "#10231f"],
  outline: "#12312a",
  bones: [
    { id: "hips", d: "Base", l: 0, a: -90, w: 5.5 },
    { id: "body1", d: "Body lower", p: "hips", l: 30, a: 0, min: -44, max: 44 },
    { id: "body2", d: "Body upper", p: "body1", l: 26, a: 0, min: -50, max: 50 },
    { id: "head", d: "Head", p: "body2", l: 22, a: 92, min: -44, max: 44 },
    { id: "ant1", d: "Antenna 1", p: "head", l: 14, a: -110, min: -80, max: 80 },
    { id: "ant2", d: "Antenna 2", p: "ant1", l: 12, a: 0, min: -80, max: 80 },
    { id: "ant3", d: "Antenna tip", p: "ant2", l: 11, a: 0, min: -80, max: 80 },
    { id: "armUpL", d: "Arm", p: "body2", l: 20, a: 150, min: -130, max: 130 },
    { id: "armLoL", d: "Hand", p: "armUpL", l: 14, a: 10, min: -130, max: 130 },
    { id: "armUpR", d: "Arm · far", p: "body2", l: 20, a: 162, min: -130, max: 130 },
    { id: "armLoR", d: "Hand · far", p: "armUpR", l: 13, a: 8, min: -130, max: 130 },
  ],
  chains: [
    { id: "body", d: "Body IK (drag = squish!)", b: ["body1", "body2"], pole: false, color: "#7cf0c8" },
    { id: "antenna", d: "Antenna IK", b: ["ant1", "ant2", "ant3"], pole: false, color: "#ffd166" },
    { id: "armL", d: "Arm IK", b: ["armUpL", "armLoL"], pole: false, color: "#5ec8ff" },
    { id: "armR", d: "Arm IK · far", b: ["armUpR", "armLoR"], pole: false, color: "#ff7a9c" },
  ],
  shapes: [
    { kind: "upperArm", bone: "armUpR", z: 0, fill: "#57b899", name: "Far arm" },
    { kind: "hand", bone: "armLoR", z: 0, scale: 1.2, fill: "#57b899", name: "Far hand" },
    { kind: "shell", bone: "body1", z: 2, role: "skin", name: "Lower blob", sx: 2.3, sy: 1.9, x: 0 },
    { kind: "shell", bone: "body2", z: 3, role: "skin", name: "Upper blob", sx: 2.0, sy: 1.7, x: 0 },
    { kind: "belly", bone: "body1", z: 4, role: "white", name: "Tummy", sx: 1.7, sy: 1.3, x: 6, y: 6 },
    { kind: "tail", bone: "ant1", z: 5, role: "cloth2", name: "Antenna", sx: 1.6, sy: 0.5 },
    { kind: "upperArm", bone: "armUpL", z: 6, role: "cloth", name: "Arm", scale: 1.1 },
    { kind: "hand", bone: "armLoL", z: 6, scale: 1.35, role: "cloth", name: "Hand" },
    { kind: "spark", bone: "ant3", z: 7, scale: 1.3, x: 6, role: "accent", name: "Antenna spark" },
    { kind: "head", bone: "head", z: 8, role: "skin", name: "Head", sx: 1.9, sy: 1.7, x: -4 },
    { kind: "eye", bone: "head", z: 9, role: "white", name: "Eye", scale: 1.7, x: 12, y: -5 },
    { kind: "pupil", bone: "head", z: 10, role: "eye", name: "Pupil", scale: 1.7, x: 15, y: -4 },
    { kind: "mouth", bone: "head", z: 10, role: "dark", name: "Mouth", scale: 1.5, x: 12, y: 7 },
  ],
};


/* --------------------------------------------------------------------- cat */

const CAT: RigDef = {
  id: "cat",
  label: "Nibbles the Cat",
  hint: "Quadruped · IK paws & tail · prowl demo · turn it with the root bone",
  palette: "cat",
  root: { x: -14, y: -4 },
  ground: 62,
  frames: 24,
  fps: 24,
  demo: "prowl",
  bg: ["#3b3358", "#191428"],
  outline: "#241a12",
  bones: [
    { id: "hips", d: "Hips", l: 0, a: 0, w: 5 },
    { id: "spine", d: "Spine", p: "hips", l: 34, a: -5, min: -16, max: 16 },
    { id: "chest", d: "Chest", p: "spine", l: 18, a: -3, min: -14, max: 14 },
    { id: "neck", d: "Neck", p: "chest", l: 13, a: -38, min: -34, max: 34 },
    { id: "head", d: "Head", p: "neck", l: 22, a: 34, min: -34, max: 34 },
    { id: "jaw", d: "Jaw", p: "head", l: 12, a: 28, min: -6, max: 30 },
    { id: "earA", d: "Ear", p: "head", l: 15, a: -66, min: -30, max: 30 },
    { id: "earB", d: "Ear · far", p: "head", l: 14, a: -46, min: -30, max: 30 },

    { id: "frontUp", d: "Front leg", p: "chest", l: 20, a: 96, min: -46, max: 52 },
    { id: "frontLo", d: "Front shin", p: "frontUp", l: 18, a: -6, min: -6, max: 120 },
    { id: "frontPaw", d: "Front paw", p: "frontLo", l: 9, a: -84 },
    { id: "frontUpB", d: "Front leg · far", p: "chest", l: 19, a: 102, min: -46, max: 52 },
    { id: "frontLoB", d: "Front shin · far", p: "frontUpB", l: 17, a: -4, min: -6, max: 120 },
    { id: "frontPawB", d: "Front paw · far", p: "frontLoB", l: 8, a: -86 },

    { id: "backUp", d: "Back leg", p: "hips", l: 22, a: 108, min: -46, max: 52 },
    { id: "backLo", d: "Back shin", p: "backUp", l: 18, a: -8, min: -6, max: 120 },
    { id: "backPaw", d: "Back paw", p: "backLo", l: 9, a: -80 },
    { id: "backUpB", d: "Back leg · far", p: "hips", l: 21, a: 114, min: -46, max: 52 },
    { id: "backLoB", d: "Back shin · far", p: "backUpB", l: 17, a: -6, min: -6, max: 120 },
    { id: "backPawB", d: "Back paw · far", p: "backLoB", l: 8, a: -82 },

    { id: "tail1", d: "Tail 1", p: "hips", l: 26, a: 176, min: -46, max: 46 },
    { id: "tail2", d: "Tail 2", p: "tail1", l: 24, a: 8, min: -44, max: 44 },
    { id: "tail3", d: "Tail tip", p: "tail2", l: 22, a: 8, min: -44, max: 44 },
  ],
  chains: [
    { id: "frontLeg", d: "Front leg IK", b: ["frontUp", "frontLo"], pole: true, color: "#7cf0c8" },
    { id: "frontLegB", d: "Front leg IK · far", b: ["frontUpB", "frontLoB"], pole: true, color: "#5ec8ff" },
    { id: "backLeg", d: "Back leg IK", b: ["backUp", "backLo"], pole: true, color: "#ffb347" },
    { id: "backLegB", d: "Back leg IK · far", b: ["backUpB", "backLoB"], pole: true, color: "#ff7a9c" },
    { id: "tail", d: "Tail IK", b: ["tail1", "tail2", "tail3"], pole: false, color: "#ffd166" },
  ],
  shapes: [
    { kind: "tail", bone: "tail1", z: 0, fill: "#c9843c", name: "Tail 1", sy: 1.05 },
    { kind: "tail", bone: "tail2", z: 0, fill: "#c9843c", name: "Tail 2", scale: 0.9 },
    { kind: "tailTuft", bone: "tail3", z: 0, role: "white", name: "Tail tip", scale: 0.75 },
    { kind: "thigh", bone: "frontUpB", z: 1, fill: "#d18f4c", name: "Far front leg" },
    { kind: "shin", bone: "frontLoB", z: 1, fill: "#d18f4c", name: "Far front shin" },
    { kind: "paw", bone: "frontPawB", z: 1, fill: "#3a2d22", name: "Far front paw", scale: 1.2 },
    { kind: "thigh", bone: "backUpB", z: 1, fill: "#c9843c", name: "Far back leg", scale: 1.1 },
    { kind: "shin", bone: "backLoB", z: 1, fill: "#c9843c", name: "Far back shin" },
    { kind: "paw", bone: "backPawB", z: 1, fill: "#3a2d22", name: "Far back paw", scale: 1.2 },
    { kind: "shell", bone: "spine", z: 4, role: "skin", name: "Body", sx: 1.05, sy: 1.0, y: -2 },
    { kind: "shell", bone: "chest", z: 4, role: "cloth", name: "Chest", sx: 0.85, sy: 0.95 },
    { kind: "belly", bone: "spine", z: 5, role: "white", name: "Tummy", sx: 0.62, sy: 0.5, x: 8, y: 9 },
    { kind: "thigh", bone: "frontUp", z: 6, role: "skin", name: "Front leg" },
    { kind: "shin", bone: "frontLo", z: 6, role: "skin", name: "Front shin" },
    { kind: "paw", bone: "frontPaw", z: 6, role: "shoe", scale: 1.35, name: "Front paw" },
    { kind: "thigh", bone: "backUp", z: 6, role: "skin", scale: 1.15, name: "Back leg" },
    { kind: "shin", bone: "backLo", z: 6, role: "skin", name: "Back shin" },
    { kind: "paw", bone: "backPaw", z: 6, role: "shoe", scale: 1.35, name: "Back paw" },
    { kind: "neck", bone: "neck", z: 7, role: "skin", sx: 1.0, sy: 1.25, name: "Neck" },
    { kind: "ear", bone: "earA", z: 8, role: "skin", scale: 1.5, name: "Ear" },
    { kind: "ear", bone: "earB", z: 7, fill: "#d18f4c", scale: 1.3, name: "Far ear" },
    { kind: "head", bone: "head", z: 9, role: "skin", sx: 1.35, sy: 1.3, x: -2, name: "Head" },
    { kind: "snout", bone: "head", z: 10, role: "white", scale: 0.72, x: 15, y: 3, name: "Muzzle" },
    { kind: "jaw", bone: "jaw", z: 10, role: "skin", scale: 0.9, name: "Jaw" },
    { kind: "pupil", bone: "head", z: 11, role: "eye", scale: 1.5, x: 8, y: -4, name: "Nose" },
    { kind: "eye", bone: "head", z: 11, role: "white", scale: 1.2, x: 9, y: -11, name: "Eye" },
    { kind: "pupil", bone: "head", z: 12, role: "eye", scale: 1.05, x: 12, y: -11, name: "Pupil" },
    { kind: "mouth", bone: "jaw", z: 11, role: "dark", scale: 0.8, x: 6, y: 2, name: "Mouth" },
  ],
};

/* ------------------------------------------------------------------- ninja */

const NINJA: RigDef = {
  id: "ninja",
  label: "Kage the Ninja",
  hint: "Humanoid · sword in hand · slash demo · headband & scarf",
  palette: "ninja",
  root: { x: -8, y: 2 },
  ground: 74,
  frames: 24,
  fps: 24,
  demo: "slash",
  bg: ["#2a3348", "#131722"],
  outline: "#0b0e14",
  bones: [
    { id: "hips", d: "Hips", l: 0, a: 0, w: 5.5 },
    { id: "spine", d: "Spine", p: "hips", l: 30, a: -92, min: -24, max: 26 },
    { id: "chest", d: "Chest", p: "spine", l: 18, a: 6, min: -18, max: 20 },
    { id: "neck", d: "Neck", p: "chest", l: 10, a: -6, min: -26, max: 28 },
    { id: "head", d: "Head", p: "neck", l: 22, a: 84, min: -34, max: 34 },
    { id: "bandL", d: "Headband tail", p: "head", l: 20, a: 150, min: -60, max: 60 },
    { id: "bandL2", d: "Headband tail 2", p: "bandL", l: 16, a: 6, min: -60, max: 60 },

    { id: "armUpF", d: "Upper arm", p: "chest", l: 27, a: 160, min: -60, max: 110 },
    { id: "armLoF", d: "Forearm", p: "armUpF", l: 25, a: 7, min: -130, max: 10 },
    { id: "handF", d: "Hand", p: "armLoF", l: 9, a: 0 },
    { id: "sword", d: "Sword", p: "handF", l: 38, a: 6 },
    { id: "armUpB", d: "Upper arm · far", p: "chest", l: 26, a: 168, min: -60, max: 110 },
    { id: "armLoB", d: "Forearm · far", p: "armUpB", l: 24, a: 6, min: -130, max: 10 },
    { id: "handB", d: "Hand · far", p: "armLoB", l: 8, a: 0 },

    { id: "legUpF", d: "Thigh", p: "hips", l: 34, a: 88, min: -70, max: 66 },
    { id: "legLoF", d: "Shin", p: "legUpF", l: 32, a: -6, min: -6, max: 136 },
    { id: "footF", d: "Foot", p: "legLoF", l: 13, a: -80 },
    { id: "legUpB", d: "Thigh · far", p: "hips", l: 33, a: 96, min: -70, max: 66 },
    { id: "legLoB", d: "Shin · far", p: "legUpB", l: 31, a: -3, min: -6, max: 136 },
    { id: "footB", d: "Foot · far", p: "legLoB", l: 12, a: -82 },
  ],
  chains: [
    { id: "armF", d: "Arm IK (sword)", b: ["armUpF", "armLoF"], pole: true, color: "#7cf0c8" },
    { id: "armB", d: "Arm IK · far", b: ["armUpB", "armLoB"], pole: true, color: "#5ec8ff" },
    { id: "legF", d: "Leg IK", b: ["legUpF", "legLoF"], pole: true, color: "#ffb347" },
    { id: "legB", d: "Leg IK · far", b: ["legUpB", "legLoB"], pole: true, color: "#ff7a9c" },
    { id: "bandL", d: "Headband IK", b: ["bandL", "bandL2"], pole: false, color: "#ffd166" },
  ],
  shapes: [
    { kind: "upperArm", bone: "armUpB", z: 0, role: "cloth2", name: "Far upper arm" },
    { kind: "foreArm", bone: "armLoB", z: 0, role: "cloth", name: "Far forearm" },
    { kind: "hand", bone: "handB", z: 0, role: "cloth2", name: "Far hand" },
    { kind: "thigh", bone: "legUpB", z: 1, role: "cloth2", name: "Far thigh" },
    { kind: "shin", bone: "legLoB", z: 1, role: "cloth2", name: "Far shin" },
    { kind: "paw", bone: "footB", z: 1, role: "shoe", scale: 1.25, name: "Far foot" },
    { kind: "cape", bone: "chest", z: 2, role: "cloth2", name: "Scarf", sx: 0.55, sy: 0.5, x: -6 },
    { kind: "torso", bone: "spine", z: 3, role: "cloth", name: "Gi", sx: 1.5, sy: 1.4, x: -2 },
    { kind: "chest", bone: "chest", z: 4, role: "cloth2", name: "Wrap", sx: 1.05, sy: 1.3, x: -2 },
    { kind: "belt", bone: "spine", z: 5, role: "accent", name: "Belt", sx: 0.5, sy: 1.5, x: -4 },
    { kind: "neck", bone: "neck", z: 5, role: "cloth2", sx: 1.3, sy: 1.5, name: "Collar" },
    { kind: "thigh", bone: "legUpF", z: 6, role: "cloth", scale: 1.1, name: "Thigh" },
    { kind: "shin", bone: "legLoF", z: 6, role: "cloth2", name: "Shin" },
    { kind: "paw", bone: "footF", z: 7, role: "shoe", scale: 1.3, name: "Foot" },
    { kind: "upperArm", bone: "armUpF", z: 8, role: "cloth", scale: 1.05, name: "Upper arm" },
    { kind: "foreArm", bone: "armLoF", z: 8, role: "cloth2", name: "Forearm" },
    { kind: "hand", bone: "handF", z: 9, role: "skin", scale: 1.15, name: "Hand" },
    { kind: "sword", bone: "sword", z: 10, role: "white", name: "Sword", scale: 0.95 },
    { kind: "head", bone: "head", z: 10, role: "cloth", scale: 1.05, x: -3, name: "Hood" },
    { kind: "head", bone: "head", z: 11, role: "skin", scale: 0.92, x: -1, y: 2, name: "Face" },
    { kind: "belt", bone: "head", z: 12, role: "accent", name: "Headband", sx: 0.72, sy: 1.15, x: -2, y: -5 },
    { kind: "eye", bone: "head", z: 13, role: "white", scale: 1.15, x: 8, y: -2, name: "Eye" },
    { kind: "pupil", bone: "head", z: 13, role: "eye", scale: 1.0, x: 10, y: -2, name: "Pupil" },
    { kind: "tail", bone: "bandL", z: 9, role: "accent", name: "Headband tail", sx: 1.1, sy: 0.35 },
    { kind: "tail", bone: "bandL2", z: 9, role: "accent", name: "Headband tail 2", sx: 1.0, sy: 0.25 },
  ],
};

/* -------------------------------------------------------------------- bird */

const BIRD: RigDef = {
  id: "bird",
  label: "Pip the Falcon",
  hint: "Flying bird · wing IK · tail fan · flap demo",
  palette: "bird",
  root: { x: -6, y: 0 },
  ground: null,
  frames: 24,
  fps: 24,
  demo: "flap",
  bg: ["#2c4a7c", "#101a30"],
  outline: "#101a2e",
  bones: [
    { id: "hips", d: "Body", l: 0, a: 0, w: 5 },
    { id: "body", d: "Torso", p: "hips", l: 30, a: -6, min: -18, max: 18 },
    { id: "chest", d: "Chest", p: "body", l: 16, a: -2, min: -16, max: 16 },
    { id: "neck", d: "Neck", p: "chest", l: 12, a: -32, min: -32, max: 32 },
    { id: "head", d: "Head", p: "neck", l: 18, a: 26, min: -30, max: 30 },
    { id: "beak", d: "Beak", p: "head", l: 16, a: 2, min: -20, max: 20 },
    { id: "crest", d: "Crest", p: "head", l: 14, a: -108, min: -30, max: 30 },

    { id: "wingUp", d: "Wing arm", p: "chest", l: 22, a: -108, min: -80, max: 70 },
    { id: "wingLo", d: "Wing hand", p: "wingUp", l: 26, a: 24, min: -80, max: 80 },
    { id: "wingUpB", d: "Wing arm · far", p: "chest", l: 21, a: -98, min: -80, max: 70 },
    { id: "wingLoB", d: "Wing hand · far", p: "wingUpB", l: 25, a: 22, min: -80, max: 80 },

    { id: "legUp", d: "Leg", p: "hips", l: 16, a: 118, min: -40, max: 40 },
    { id: "legLo", d: "Talon", p: "legUp", l: 14, a: -46, min: -20, max: 110 },

    { id: "tail1", d: "Tail", p: "hips", l: 20, a: 174, min: -40, max: 40 },
    { id: "tail2", d: "Tail fan", p: "tail1", l: 18, a: 6, min: -40, max: 40 },
  ],
  chains: [
    { id: "wingL", d: "Wing IK", b: ["wingUp", "wingLo"], pole: false, color: "#7cf0c8" },
    { id: "wingR", d: "Wing IK · far", b: ["wingUpB", "wingLoB"], pole: false, color: "#5ec8ff" },
    { id: "tail", d: "Tail IK", b: ["tail1", "tail2"], pole: false, color: "#ffd166" },
  ],
  shapes: [
    { kind: "tail", bone: "tail1", z: 0, role: "cloth", name: "Tail", sx: 1.1, sy: 0.9 },
    { kind: "tailTuft", bone: "tail2", z: 0, role: "accent", name: "Tail fan", scale: 0.7, sx: 1.35 },
    { kind: "wing", bone: "wingUpB", z: 1, fill: "#3f6dc0", name: "Far wing", sx: 1.2, sy: 0.72 },
    { kind: "wing", bone: "wingLoB", z: 1, fill: "#3f6dc0", name: "Far wing tip", sx: 0.95, sy: 0.6, x: -3 },
    { kind: "shin", bone: "legUp", z: 2, role: "accent", scale: 0.9, name: "Leg" },
    { kind: "paw", bone: "legLo", z: 2, role: "accent", scale: 1.0, name: "Talon" },
    { kind: "shell", bone: "body", z: 4, role: "skin", name: "Body", sx: 1.05, sy: 0.9, x: -2 },
    { kind: "shell", bone: "chest", z: 4, role: "cloth", name: "Chest", sx: 0.95, sy: 0.85, x: 1 },
    { kind: "belly", bone: "body", z: 5, role: "accent", name: "Breast", sx: 0.85, sy: 0.7, x: 12, y: 8 },
    { kind: "wing", bone: "wingUp", z: 6, role: "skin", name: "Wing", sx: 1.3, sy: 0.8 },
    { kind: "tail", bone: "wingUp", z: 7, role: "cloth", name: "Wing coverts", sx: 1.0, sy: 0.42, x: 2, y: -4 },
    { kind: "wing", bone: "wingLo", z: 6, role: "skin", name: "Wing tip", sx: 1.0, sy: 0.66, x: -3 },
    { kind: "neck", bone: "neck", z: 7, role: "cloth", sx: 0.95, sy: 1.15, name: "Neck" },
    { kind: "head", bone: "head", z: 8, role: "skin", scale: 1.25, x: -2, name: "Head" },
    { kind: "horn", bone: "beak", z: 9, role: "accent", sharp: true, scale: 1.35, name: "Beak" },
    { kind: "tailTuft", bone: "crest", z: 8, role: "accent", name: "Crest", scale: 0.6, sx: 0.85 },
    { kind: "eye", bone: "head", z: 9, role: "white", scale: 1.05, x: 7, y: -5, name: "Eye" },
    { kind: "pupil", bone: "head", z: 10, role: "eye", scale: 1.0, x: 9, y: -5, name: "Pupil" },
  ],
};

/* ------------------------------------------------------------------ wizard */

const WIZARD: RigDef = {
  id: "wizard",
  label: "Meryl the Wizard",
  hint: "Humanoid · staff with a live glow light · cast demo",
  palette: "wizard",
  root: { x: -6, y: 4 },
  ground: 76,
  frames: 32,
  fps: 24,
  demo: "cast",
  bg: ["#2c2450", "#120f22"],
  outline: "#1b1630",
  bones: [
    { id: "hips", d: "Hips", l: 0, a: 0, w: 5.5 },
    { id: "spine", d: "Spine", p: "hips", l: 30, a: -92, min: -22, max: 24 },
    { id: "chest", d: "Chest", p: "spine", l: 20, a: 4, min: -16, max: 18 },
    { id: "neck", d: "Neck", p: "chest", l: 10, a: -6, min: -24, max: 26 },
    { id: "head", d: "Head", p: "neck", l: 22, a: 84, min: -34, max: 34 },
    { id: "hat", d: "Hat", p: "head", l: 30, a: -66, min: -20, max: 20 },
    { id: "hatTip", d: "Hat tip", p: "hat", l: 18, a: 22, min: -40, max: 40 },
    { id: "beard", d: "Beard", p: "head", l: 20, a: 120, min: -30, max: 40 },

    { id: "armUpF", d: "Upper arm", p: "chest", l: 26, a: 158, min: -70, max: 100 },
    { id: "armLoF", d: "Forearm", p: "armUpF", l: 24, a: 6, min: -130, max: 10 },
    { id: "handF", d: "Hand", p: "armLoF", l: 9, a: 0 },
    { id: "staff", d: "Staff", p: "handF", l: 70, a: -104 },
    { id: "armUpB", d: "Upper arm · far", p: "chest", l: 25, a: 172, min: -70, max: 100 },
    { id: "armLoB", d: "Forearm · far", p: "armUpB", l: 23, a: 5, min: -130, max: 10 },
    { id: "handB", d: "Hand · far", p: "armLoB", l: 8, a: 0 },

    { id: "legUpF", d: "Thigh", p: "hips", l: 32, a: 90, min: -60, max: 60 },
    { id: "legLoF", d: "Shin", p: "legUpF", l: 30, a: -6, min: -6, max: 120 },
    { id: "footF", d: "Foot", p: "legLoF", l: 13, a: -78 },
    { id: "legUpB", d: "Thigh · far", p: "hips", l: 31, a: 96, min: -60, max: 60 },
    { id: "legLoB", d: "Shin · far", p: "legUpB", l: 29, a: -3, min: -6, max: 120 },
    { id: "footB", d: "Foot · far", p: "legLoB", l: 12, a: -80 },
  ],
  chains: [
    { id: "armF", d: "Arm IK (staff)", b: ["armUpF", "armLoF"], pole: true, color: "#7cf0c8" },
    { id: "armB", d: "Arm IK · far", b: ["armUpB", "armLoB"], pole: true, color: "#5ec8ff" },
    { id: "legF", d: "Leg IK", b: ["legUpF", "legLoF"], pole: true, color: "#ffb347" },
    { id: "legB", d: "Leg IK · far", b: ["legUpB", "legLoB"], pole: true, color: "#ff7a9c" },
  ],
  shapes: [
    { kind: "upperArm", bone: "armUpB", z: 0, fill: "#5b449c", name: "Far upper arm" },
    { kind: "foreArm", bone: "armLoB", z: 0, fill: "#6b54c8", name: "Far forearm" },
    { kind: "hand", bone: "handB", z: 0, role: "skin", name: "Far hand" },
    { kind: "thigh", bone: "legUpB", z: 1, role: "cloth2", name: "Far thigh" },
    { kind: "shin", bone: "legLoB", z: 1, role: "cloth2", name: "Far shin" },
    { kind: "paw", bone: "footB", z: 1, role: "shoe", name: "Far boot", scale: 1.2 },
    { kind: "torso", bone: "spine", z: 3, role: "cloth", name: "Robe", sx: 1.75, sy: 1.55, x: -4 },
    { kind: "cape", bone: "chest", z: 2, role: "cloth2", name: "Cloak back", sx: 0.7, sy: 0.6, x: -8 },
    { kind: "belly", bone: "spine", z: 4, role: "accent", name: "Robe trim", sx: 1.3, sy: 1.0, x: 6, y: 14 },
    { kind: "thigh", bone: "legUpF", z: 6, role: "cloth", name: "Thigh" },
    { kind: "shin", bone: "legLoF", z: 6, role: "cloth2", name: "Shin" },
    { kind: "paw", bone: "footF", z: 7, role: "shoe", scale: 1.3, name: "Boot" },
    { kind: "upperArm", bone: "armUpF", z: 8, role: "cloth", scale: 1.1, name: "Sleeve" },
    { kind: "foreArm", bone: "armLoF", z: 8, role: "cloth", name: "Sleeve cuff" },
    { kind: "hand", bone: "handF", z: 9, role: "skin", scale: 1.2, name: "Hand" },
    { kind: "tail", bone: "staff", z: 10, role: "hair", name: "Staff", sx: 1.0, sy: 0.16 },
    { kind: "ball", bone: "staff", z: 11, role: "accent", name: "Orb", scale: 0.26, x: 74 },
    { kind: "spark", bone: "staff", z: 12, role: "white", name: "Orb sparkle", scale: 0.16, x: 74 },
    { kind: "head", bone: "head", z: 10, role: "skin", scale: 1.05, x: 1, y: 1, name: "Head" },
    { kind: "snout", bone: "beard", z: 11, role: "hair", name: "Beard", scale: 1.15, sy: 1.0, x: -2, y: -2 },
    { kind: "hat", bone: "hat", z: 12, role: "cloth2", name: "Hat", scale: 1.05, rot: 90, y: -6 },
    { kind: "tail", bone: "hatTip", z: 12, role: "cloth2", name: "Hat tip", sx: 1.35, sy: 0.34, y: -6 },
    { kind: "pupil", bone: "hatTip", z: 13, role: "accent", name: "Hat star", scale: 1.1, y: -6 },
    { kind: "eye", bone: "head", z: 13, role: "white", scale: 0.95, x: 10, y: -4, name: "Eye" },
    { kind: "pupil", bone: "head", z: 14, role: "eye", scale: 0.9, x: 12, y: -4, name: "Pupil" },
    { kind: "mouth", bone: "head", z: 13, role: "dark", scale: 0.9, x: 11, y: 4, name: "Mouth" },
  ],
};

const BLANK: RigDef = {
  id: "blank",
  label: "Empty stage",
  hint: "Start from nothing: add bones, drop parts on them",
  palette: "cartoon",
  root: { x: 0, y: 40 },
  ground: 100,
  frames: 48,
  fps: 24,
  demo: null,
  bg: ["#262a4a", "#14162a"],
  bones: [{ id: "hips", d: "Hips", l: 0, a: 0, w: 5.5 }],
  shapes: [{ kind: "hipbox", bone: "hips", z: 0, role: "cloth2", name: "Base", sx: 1.8, sy: 1.4 }],
};

export const RIGS: RigDef[] = [KID, CAT, NINJA, ROBOT, DRAGON, BIRD, WIZARD, BLOB, BLANK];
export const RIG_MAP = new Map(RIGS.map((r) => [r.id, r]));
